return {
    "stevearc/conform.nvim",
    event = "VeryLazy",
    opts = {
        formatters_by_ft = {
            javascript = { "biome" },
            javascriptreact = { "biome" },
            json = { "biome" },
            jsonc = { "biome" },
            typescript = { "biome" },
            typescriptreact = { "biome" },
            astro = { "biome" },
            svelte = { "biome" },
            vue = { "prettier" },
            ["css"] = { "prettier" },
            ["scss"] = { "prettier" },
            ["less"] = { "prettier" },
            ["html"] = { "prettier" },
            ["yaml"] = { "prettier" },
            ["markdown"] = { "prettier" },
            ["markdown.mdx"] = { "prettier" },
            ["graphql"] = { "prettier" },
            ["handlebars"] = { "prettier" },
            ["python"] = { "isort", "black" },
        },
    },
}
